"""Studio 2026 template pack — 16 additional industry templates authored in the new design system.

These reuse the same page builder as the original pack, so they get the CTA modal forms, locks,
overview sync and export pipeline for free. Each one is flagged `studio: True` so the gallery can
badge it as a new-design template and tenants created from it start on the new skin.
"""
from site_content import NICHES, LOOKS, MOODS, img  # noqa: F401

SECTIONS = ["services", "stats", "gallery", "testimonials", "team", "faq", "cta"]


def _mk(brand, industry, badge, title, sub, cta, cta2, hero, gallery, video,
        services, stats, quotes, faq, about, team, email, phone, address, mood="moody"):
    h, ssub, items = services
    return {
        "brand": brand, "industry": industry, "mood": mood, "badge": badge, "title": title, "sub": sub,
        "cta": cta, "cta2": cta2, "hero": img(hero), "video": video, "gallery": gallery,
        "sections": SECTIONS, "services": (h, ssub, items), "stats": stats, "quotes": quotes,
        "faq": faq, "about": about, "team": team, "email": email, "phone": phone, "address": address,
        "primary": "#4F46E5", "secondary": "#0EA5E9",
    }


def _vid(q):
    return f"https://www.youtube.com/embed?listType=search&list={q.replace(' ', '+')}"


G1 = ["photo-1521737604893-d14cc237f11d", "photo-1497366754035-f200968a6e72", "photo-1524758631624-e2822e304c36",
      "photo-1600585154340-be6161a56a0c", "photo-1521791136064-7986c2920216", "photo-1454165804606-c3d57bc86b40"]
G2 = ["photo-1517245386807-bb43f82c33c4", "photo-1519494026892-80bbd2d6fd0d", "photo-1505751172876-fa1923c5c528",
      "photo-1576091160399-112ba8d25d1d", "photo-1538108149393-fbbd81895907", "photo-1551076805-e1869033e561"]
G3 = ["photo-1581091226825-a6a2a5aee158", "photo-1516321318423-f06f85e504b3", "photo-1531482615713-2afd69097998",
      "photo-1522202176988-66273c2fd55f", "photo-1553877522-43269d4ea984", "photo-1517048676732-d65bc937f952"]

_T = [
    ("veterinary", _mk("Willow Creek Veterinary", "Veterinary", "AAHA accredited · 24/7 emergency care",
        "Gentle care for the ones who wait by the door.",
        "Full-service small-animal medicine, surgery and dentistry, with same-week appointments and a fear-free exam room.",
        "Book an appointment", "Meet our vets", "photo-1450778869180-41d0601e046e", G2, _vid("veterinary clinic tour"),
        ("Care", "Everything your pet needs under one roof.", [
            ("Wellness & vaccines", "Annual exams, titre testing and a vaccine plan matched to how your pet actually lives.", "Heart"),
            ("Surgery & dentistry", "Digital dental radiography, monitored anaesthesia and same-day discharge for most procedures.", "Activity"),
            ("Urgent care", "Walk-in triage until 10pm, seven days, with an on-call vet overnight.", "Clock")]),
        [("18 yrs", "Caring for this neighbourhood"), ("4.9/5", "From 1,400 reviews"), ("Same week", "Routine appointments"), ("24/7", "Emergency on-call")],
        [("They found the mass early and walked us through every option without pressure. Two years on, Rosie is still stealing socks.", "Dana Whitfield", "Client since 2019"),
         ("The fear-free room changed everything for our rescue. She walks in on her own now.", "Marcus Aldridge", "Client")],
        [("Do you take walk-ins?", "Yes for urgent care until 10pm; routine exams are booked so nobody waits with an anxious pet."),
         ("Do you offer payment plans?", "We accept all major pet insurers and offer third-party financing on treatment over $500."),
         ("Can I stay with my pet?", "Always, for exams and most procedures up to sedation.")],
        ("A practice built around the animals, not the schedule.", "Willow Creek opened in 2008 above a feed store with one vet and a borrowed X-ray machine. We now run four exam rooms, an in-house lab and a surgical suite, and we still hold the same rule: nobody gets rushed."),
        [("Dr. Elena Marsh", "Owner, DVM"), ("Dr. Peter Nwosu", "Surgery & dentistry"), ("Dr. Hana Sato", "Internal medicine"), ("Cory Bell", "Head technician")],
        "care@willowcreekvet.com", "(416) 555-0142", "88 Willow Creek Road")),
    ("dental", _mk("Brightline Dental Studio", "Dental", "Same-day crowns · Sedation options",
        "Dentistry that doesn't feel like dentistry.",
        "Digital scanning, same-day ceramics and a team that explains the plan before anything touches your teeth.",
        "Book a consultation", "See patient results", "photo-1588776814546-1ffcf47267a5", G2, _vid("modern dental clinic"),
        ("Treatments", "Preventive, restorative and cosmetic care in one visit where possible.", [
            ("Hygiene & prevention", "Ultrasonic cleaning, oral cancer screening and a recall interval based on your risk, not a calendar.", "Sparkles"),
            ("Same-day crowns", "Intraoral scan, milled ceramic and fitted in a single ninety-minute appointment.", "Zap"),
            ("Invisible aligners", "A full digital plan you can preview before you commit, with refinements included.", "Smile")]),
        [("90 min", "Scan to fitted crown"), ("0%", "Financing over 12 months"), ("12k+", "Patients treated"), ("4.9/5", "Google rating")],
        [("I hadn't seen a dentist in nine years. They never once made me feel bad about it.", "Priya Raman", "Patient"),
         ("Crown done at lunch, back at work by two. No temporary, no second visit.", "Owen Clarke", "Patient")],
        [("Do you offer sedation?", "Yes — nitrous oxide and oral sedation, with IV sedation by a visiting anaesthetist."),
         ("Are you taking new patients?", "Yes, with new-patient exams usually available inside two weeks."),
         ("Do you direct bill insurance?", "We bill all major insurers directly so you only pay the balance.")],
        ("Calm, modern, unhurried.", "Brightline was founded on a simple observation: most dental anxiety comes from not knowing what happens next. So we scan, we show you the screen, we quote in writing, and we only begin when you say go."),
        [("Dr. Amara Boateng", "Principal dentist"), ("Dr. Liam Petrov", "Prosthodontics"), ("Nadia Haddad", "Lead hygienist"), ("Ben Ortiz", "Treatment coordinator")],
        "hello@brightlinedental.com", "(416) 555-0177", "410 Queen Street West")),
    ("accounting", _mk("Ledgerhouse Accounting", "Accounting", "CPA firm · Cloud-first bookkeeping",
        "Numbers you can finally trust, on the third of every month.",
        "Bookkeeping, payroll, corporate tax and CFO-level advice for founder-led businesses between $500K and $20M.",
        "Request a consultation", "Download our pricing", "photo-1554224155-6726b3ff858f", G1, _vid("small business accounting"),
        ("Services", "One team for the books, the filings and the decisions.", [
            ("Monthly bookkeeping", "Reconciled books and a plain-English management pack in your inbox by the third business day.", "BookOpen"),
            ("Tax & compliance", "Corporate returns, GST/HST, T4s and year-end, filed early and defended if reviewed.", "ShieldCheck"),
            ("CFO advisory", "Cash-flow modelling, pricing reviews and lender-ready forecasts, quarterly.", "TrendingUp")]),
        [("3rd", "Business day close"), ("$0", "In late-filing penalties, ever"), ("310", "Owner-managed clients"), ("22 yrs", "In practice")],
        [("We went from finding out we were profitable in April to knowing it every month.", "Sasha Nolan", "Founder, Nolan Fabrication"),
         ("They caught $41,000 of missed input credits in the first review.", "Diego Ferreira", "Director, Ferreira Logistics")],
        [("Do you work with my software?", "Yes — QuickBooks Online, Xero and Dext, and we'll migrate you free of charge."),
         ("Is pricing fixed?", "Fixed monthly fee agreed in advance. No surprise invoices, no billable emails."),
         ("Can you fix a year of messy books?", "That's most of what we do. We quote catch-up work separately and flat.")],
        ("Accountants who answer the phone.", "Ledgerhouse was started by two CPAs who left mid-size firms because clients only heard from them at year-end. We cap each manager's client list so the person who knows your file is the person who picks up."),
        [("Grace Okonkwo", "Managing partner, CPA"), ("Tomás Rivera", "Tax partner, CPA"), ("Ingrid Halvorsen", "Bookkeeping lead"), ("Sam Whitaker", "Advisory manager")],
        "advice@ledgerhouse.com", "(416) 555-0155", "1200 Bay Street, Suite 705")),
    ("landscaping", _mk("Stonefield Landscape Co.", "Landscaping", "Design-build · Fully insured crews",
        "Gardens that look intentional in every season.",
        "Design-build landscaping, interlock and full-property maintenance for homes and grounds across the region.",
        "Get a quote", "See our portfolio", "photo-1558904541-efa843a96f01", G3, _vid("landscape design build"),
        ("What we do", "Designed, built and maintained by the same crew.", [
            ("Landscape design", "Scaled plans and 3D renders so you can walk the garden before we break ground.", "PenTool"),
            ("Interlock & masonry", "Patios, steps and retaining walls built on properly compacted base, guaranteed five years.", "Layers"),
            ("Seasonal care", "Spring cleanups, weekly maintenance, pruning and winter protection on one agreement.", "Leaf")]),
        [("5 yr", "Workmanship warranty"), ("400+", "Properties transformed"), ("2-4 wks", "Typical project start"), ("100%", "WSIB covered crews")],
        [("The patio survived three winters without a single heave. Our neighbours all used them after.", "Helen Vasquez", "Homeowner, Oakridge"),
         ("They redesigned a slope we'd written off. It's now the part of the garden we use most.", "Ravi Chandra", "Homeowner")],
        [("When should I book?", "Design in winter, build in spring. Our build calendar usually fills by March."),
         ("Do you handle permits?", "Yes, including grading and any pool or fence permits your project needs."),
         ("Do you offer maintenance after the build?", "Yes, and our crews already know your irrigation and plantings.")],
        ("Built by people who like being outside.", "Stonefield started with one truck and a stone splitter in 2011. We kept design and build under one roof so nobody can blame the drawings, and we maintain what we build so we're accountable to it for years."),
        [("Nathan Cole", "Founder & designer"), ("Marisol Duarte", "Build manager"), ("Erik Lindgren", "Masonry lead"), ("Jade Kim", "Horticulturist")],
        "quotes@stonefieldlandscape.com", "(416) 555-0193", "3400 Concession Road 6")),
    ("photography", _mk("Aperture North Studio", "Photography", "Editorial & brand photography",
        "Pictures that still work three years from now.",
        "Brand, product and editorial photography for companies that are tired of stock imagery.",
        "Enquire about a shoot", "View the portfolio", "photo-1452587925148-ce544e77e70d", G3, _vid("brand photography behind the scenes"),
        ("Studio services", "Shot, retouched and delivered ready for every channel.", [
            ("Brand libraries", "A day on site, ninety finished images, licensed in perpetuity across every channel.", "Camera"),
            ("Product & e-commerce", "Consistent lighting, ghost mannequin and cut-outs delivered on a two-day turnaround.", "Package"),
            ("Editorial & portraits", "Considered portraiture for annual reports, press and leadership pages.", "Aperture")]),
        [("90", "Finished frames per shoot day"), ("48 hr", "Product turnaround"), ("140", "Brands photographed"), ("2 wks", "Typical booking lead time")],
        [("Our conversion lifted 18% on the product pages we reshot. Same products, better pictures.", "Claire Dubois", "Head of Ecommerce, Maison Verde"),
         ("They made a warehouse look like a design studio and made our engineers look comfortable. Both miracles.", "Andrew Pyke", "CMO, Northline")],
        [("Do we get the raw files?", "Finished, retouched files are included; raws are available for an additional archive fee."),
         ("Where do you shoot?", "Our studio, your premises, or on location — travel inside the region is included."),
         ("How do licences work?", "Perpetual, unlimited internal and marketing use. We only ask before reselling.")],
        ("A studio, not an agency.", "Aperture North is a small team that would rather shoot than pitch. We quote by the shoot day, retouch in house and hand over files organised the way your marketing team actually files them."),
        [("Iris Lindqvist", "Founder & photographer"), ("Kwame Asante", "Photographer"), ("Lena Fischer", "Retoucher"), ("Owen Ridley", "Producer")],
        "studio@aperturenorth.com", "(416) 555-0128", "Unit 4, 88 Sudbury Street")),
    ("automotive", _mk("Ridgeway Auto Service", "Automotive", "Licensed technicians · 2-year warranty",
        "Honest repairs, explained before we start.",
        "Diagnostics, brakes, suspension and scheduled maintenance for every major make, with photos of what we found.",
        "Book a service", "Get an estimate", "photo-1486262715619-67b85e0b08d3", G1, _vid("auto repair shop"),
        ("Workshop", "Diagnose properly, fix once.", [
            ("Diagnostics", "Manufacturer-level scan tools and a written explanation with photos of the actual fault.", "Gauge"),
            ("Brakes & suspension", "OE-grade parts, machined rotors and a two-year parts-and-labour warranty.", "Disc"),
            ("Maintenance plans", "Service intervals tracked for you, so nothing lapses on a lease or warranty.", "CalendarCheck")]),
        [("2 yr", "Parts & labour warranty"), ("Photos", "Of every fault, before approval"), ("11", "Licensed technicians"), ("4.8/5", "1,900 reviews")],
        [("They sent photos of the worn bushing, quoted it, and came in under the quote. Unheard of.", "Bianca Rossi", "Customer"),
         ("Second opinion saved me a transmission I didn't need. I don't go anywhere else now.", "Tyler Mensah", "Customer")],
        [("Do you offer loaners?", "Yes on jobs over four hours, plus free local shuttle."),
         ("Will service here void my warranty?", "No. We log every service to manufacturer schedule and keep the records."),
         ("Do you take EVs?", "Yes, high-voltage certified for brakes, suspension, thermal and 12V systems.")],
        ("Third generation, same corner.", "Ridgeway has been on this corner since 1974. Three things haven't changed: we show you the broken part, we quote before we turn a bolt, and we stand behind the work for two years."),
        [("Dale Ridgeway", "Owner & licensed tech"), ("Anna Kovacs", "Service manager"), ("Femi Adeyemi", "Diagnostics lead"), ("Chris Tanaka", "EV specialist")],
        "service@ridgewayauto.com", "(416) 555-0166", "2210 Ridgeway Avenue")),
    ("beauty", _mk("Lumière Beauty Bar", "Beauty & Spa", "Clean products · Licensed aestheticians",
        "An hour that gives you the week back.",
        "Facials, lashes, brows and body treatments in a quiet studio that never double-books a therapist.",
        "Reserve your visit", "View the menu", "photo-1560750588-73207b1ef5b8", G2, _vid("modern beauty spa treatment"),
        ("Treatments", "Results-driven, never rushed.", [
            ("Signature facials", "A skin analysis first, then a protocol chosen for your barrier — not a fixed menu item.", "Sparkles"),
            ("Lashes & brows", "Lash extensions, lifts and brow lamination with mapping suited to your features.", "Eye"),
            ("Body & massage", "Lymphatic massage, body wraps and pre-event treatments in a private room.", "Flower")]),
        [("60-90", "Minutes per treatment"), ("1:1", "Never double-booked"), ("Clean", "Fragrance-free product line"), ("9k+", "Treatments delivered")],
        [("The only facial that's ever calmed my rosacea instead of setting it off.", "Nour El-Amin", "Client"),
         ("Booked for a wedding, stayed for four years.", "Chloe Barrington", "Client")],
        [("Do you take walk-ins?", "Occasionally, but the studio runs on appointments so nobody overlaps."),
         ("Are treatments safe in pregnancy?", "Most are; we adjust products and positioning and will tell you what to skip."),
         ("What's your cancellation policy?", "Twenty-four hours, and life happens — one grace cancellation a year.")],
        ("Small, quiet and deliberately unhurried.", "Lumière has four rooms and no upsell script. Our therapists are salaried rather than commissioned, so the treatment you're recommended is the one your skin needs."),
        [("Sylvie Aubert", "Founder & aesthetician"), ("Maya Prasad", "Lead therapist"), ("Jonah Wells", "Lash artist"), ("Rita Moreno", "Massage therapist")],
        "book@lumierebeautybar.com", "(416) 555-0119", "56 Ossington Avenue")),
    ("insurance", _mk("Harbourstone Insurance Group", "Insurance", "Independent brokers · 30+ carriers",
        "Cover that holds up on the worst day of the year.",
        "Independent brokers for home, auto, commercial and life — we shop thirty carriers so you don't shop one.",
        "Request a quote", "Talk to a broker", "photo-1450101499163-c8848c66ca85", G1, _vid("insurance broker consultation"),
        ("Coverage", "Advice first, policy second.", [
            ("Home & auto", "Bundled coverage reviewed annually so your limits keep pace with replacement cost.", "Home"),
            ("Commercial lines", "Liability, property, fleet and cyber for businesses from one van to two hundred staff.", "Building2"),
            ("Life & disability", "Term, whole life and income protection modelled against what your family actually needs.", "HeartHandshake")]),
        [("30+", "Carriers compared"), ("94%", "Claims approved first submission"), ("48 hr", "Quote turnaround"), ("6,400", "Policies managed")],
        [("Our shop burned in February. The cheque cleared in eleven days because the policy was written properly.", "Gordon Bell", "Owner, Bell Woodworking"),
         ("Same coverage, $1,100 less, and someone answers when I call.", "Amelia Stone", "Client")],
        [("Do you charge broker fees?", "No. We're paid by the carrier, so our advice costs you nothing."),
         ("Can you handle my claim for me?", "Yes — we advocate through the whole claim, including appeals."),
         ("How often should coverage be reviewed?", "Annually, and after any renovation, vehicle or business change.")],
        ("Brokers, not agents.", "Harbourstone has been independent since 1996, which means we work for the policyholder. We put coverage side by side, explain the exclusions people gloss over, and we're in the room when you claim."),
        [("Priya Sandhu", "Managing broker"), ("Callum Reid", "Commercial lines"), ("Yasmin Farouk", "Personal lines"), ("Dev Patel", "Claims advocate")],
        "quotes@harbourstoneinsurance.com", "(416) 555-0188", "77 King Street West, Floor 9")),
    ("pet_grooming", _mk("Muddy Paws Grooming", "Pet Services", "Certified groomers · One dog at a time",
        "Baths, brushes and absolutely no cages.",
        "Cage-free grooming, hand-drying and breed-standard trims in a calm studio with one dog at a time.",
        "Book a groom", "See before & after", "photo-1516734212186-a967f81ad0d7", G2, _vid("dog grooming salon"),
        ("Grooming", "One dog, one groomer, start to finish.", [
            ("Full groom", "Bath, hand-dry, breed trim, nails and ears in a single two-hour appointment.", "Scissors"),
            ("Bath & tidy", "Deshedding bath, blow-out and a face-feet-fanny tidy for coats between cuts.", "Droplets"),
            ("Puppy first visits", "A short, positive introduction so grooming never becomes something to dread.", "Heart")]),
        [("1", "Dog in the salon at a time"), ("0", "Cages, ever"), ("2 hr", "Average appointment"), ("2,800", "Happy regulars")],
        [("Our anxious spaniel actually walks in wagging now. That's everything.", "Fiona Mackenzie", "Client"),
         ("Best breed trim we've had in fifteen years of poodles.", "Robert Ellery", "Client")],
        [("How far ahead should I book?", "Regulars book their next groom on the way out; new dogs usually get in within two weeks."),
         ("Do you groom cats?", "Yes, by appointment on quiet mornings only."),
         ("What if my dog is nervous?", "Tell us first. We'll book a short meet-and-greet before any tools come out.")],
        ("A calmer kind of grooming.", "Muddy Paws was built around one rule: no dog waits in a crate. That means fewer appointments a day and a groomer who stays with your dog from bath to bow."),
        [("Georgia Fenwick", "Owner & master groomer"), ("Aiden Brooks", "Groomer"), ("Salma Rahim", "Groomer & bather"), ("Nico Alvarez", "Client care")],
        "hello@muddypawsgrooming.com", "(416) 555-0134", "19 Roncesvalles Avenue")),
    ("hvac_plumbing", _mk("Copperline Plumbing & Heating", "Plumbing", "Licensed & bonded · 24/7 emergency",
        "The plumber your neighbours already recommended.",
        "Emergency repairs, drain work, water heaters and full bathroom rough-ins, quoted before we start.",
        "Request service", "Get an estimate", "photo-1607472586893-edb57bdc0e39", G1, _vid("plumbing repair service"),
        ("Services", "Flat-rate quotes, licensed technicians.", [
            ("Emergency repairs", "Burst pipes, backups and no-heat calls answered around the clock, seven days.", "Siren"),
            ("Drains & sewers", "Camera inspection, hydro-jetting and trenchless liner repairs with video proof.", "Waves"),
            ("Water heaters", "Tank and tankless supplied, installed and permitted the same day in most cases.", "Flame")]),
        [("24/7", "Emergency response"), ("90 min", "Average arrival time"), ("Flat", "Rate quotes, not hourly"), ("15 yrs", "Licensed and bonded")],
        [("Basement flooding at 11pm on a Sunday. Truck was on the street in under an hour.", "Kate Sullivan", "Homeowner"),
         ("Camera showed the crack, liner fixed it, no excavation, no wrecked driveway.", "Hassan Karim", "Homeowner")],
        [("Do you charge for estimates?", "Diagnostics are a flat call-out fee, waived if you proceed with the repair."),
         ("Are you licensed and insured?", "Fully licensed, bonded and $5M insured — certificates on request."),
         ("Do you pull permits?", "Yes for water heaters, repipes and any rough-in work.")],
        ("Trucks stocked, phones answered.", "Copperline runs eight stocked trucks so most jobs finish on the first visit. Every technician is licensed, background-checked and paid salary rather than commission, so nobody is selling you a repipe you don't need."),
        [("Frank Delgado", "Owner, licensed plumber"), ("Sean O'Rourke", "Service manager"), ("Amrit Kaur", "Drain specialist"), ("Luca Bianchi", "Gas technician")],
        "service@copperlineplumbing.com", "(416) 555-0171", "540 Industrial Drive, Unit 3")),
    ("coworking", _mk("The Foundry Workspace", "Coworking", "Members from $180/mo · 24/7 access",
        "A desk you'll actually look forward to.",
        "Private studios, dedicated desks and meeting rooms in a converted foundry, with real coffee and quiet floors.",
        "Book a tour", "See membership plans", "photo-1497366216548-37526070297c", G1, _vid("coworking space tour"),
        ("Memberships", "Choose the amount of quiet you need.", [
            ("Private studios", "Lockable two to twelve person studios with your own door, glass and thermostat.", "DoorClosed"),
            ("Dedicated desks", "The same desk, monitor and locker every day, on a rolling month agreement.", "Monitor"),
            ("Meeting rooms", "Four bookable rooms with proper AV, included hours on every plan.", "Presentation")]),
        [("$180", "Entry membership per month"), ("24/7", "Member access"), ("94%", "Occupancy"), ("1 mo", "Notice, never a year")],
        [("We moved eleven people in and cancelled a five-year lease. No regrets at all.", "Adaora Nnamdi", "Founder, Relay Studio"),
         ("Quiet floors that are genuinely quiet. That's the whole reason I'm still here.", "Michael Sørensen", "Independent consultant")],
        [("Can I try it first?", "Yes — book a tour and we'll give you a free day pass, no card required."),
         ("Is there parking?", "Underground parking and secure bike storage with showers on level one."),
         ("Can I bring clients?", "Guests are always welcome, and meeting room hours come with every plan.")],
        ("An old foundry with good bones.", "We restored a 1912 foundry rather than fitting out a tower: high windows, brick, and floors laid out so calls never bleed into focus work. Members stay an average of two and a half years, which we take as the review that matters."),
        [("Rosa Delacroix", "Community director"), ("Tobias Lang", "Operations"), ("Nia Campbell", "Member experience"), ("Victor Aguilar", "Facilities")],
        "hello@thefoundryworkspace.com", "(416) 555-0102", "12 Foundry Lane")),
    ("wellness", _mk("Stillwater Therapy", "Mental Health", "Registered psychotherapists · Virtual or in person",
        "Somewhere to put it all down.",
        "Individual, couples and trauma therapy with registered psychotherapists, available evenings and weekends.",
        "Book a consultation", "How therapy works", "photo-1544027993-37dbfe43562a", G2, _vid("therapy counselling session"),
        ("How we help", "Matched to the right therapist, not the next available one.", [
            ("Individual therapy", "CBT, ACT and EMDR for anxiety, burnout, grief and long-standing patterns.", "Brain"),
            ("Couples counselling", "Emotionally focused work for communication, trust and life transitions.", "Users"),
            ("Trauma & EMDR", "Paced, structured trauma processing with clinicians trained specifically for it.", "ShieldCheck")]),
        [("48 hr", "To a first appointment"), ("Direct", "Billing to most insurers"), ("Eve/Wknd", "Sessions available"), ("15 min", "Free matching call")],
        [("The matching call mattered more than I expected. Third therapist in ten years, first one that fit.", "Anonymous", "Client"),
         ("We came in ready to end it. Eight months later we're planning things again.", "Anonymous", "Couples client")],
        [("Is it covered by insurance?", "Psychotherapy is covered by most extended health plans; we direct bill where possible."),
         ("Virtual or in person?", "Either, and you can switch week to week."),
         ("What if it isn't the right fit?", "Tell us and we'll rematch you inside the practice at no cost.")],
        ("Clinicians first, clinic second.", "Stillwater was founded by three registered psychotherapists who wanted small caseloads and proper supervision. Every clinician here holds current registration and takes on fewer clients so sessions aren't back to back."),
        [("Dr. Miriam Feld", "Clinical director, RP"), ("Jonah Kirkland", "RP, trauma & EMDR"), ("Alina Petrova", "RP, couples"), ("Sean Whitmore", "Intake coordinator")],
        "care@stillwatertherapy.com", "(416) 555-0147", "300 Danforth Avenue, Suite 210")),
    ("cleaning", _mk("Clearview Cleaning Co.", "Cleaning Services", "Bonded staff · Eco-certified products",
        "Come home to a place that smells like nothing.",
        "Recurring home cleaning, deep cleans and move-out service by bonded, salaried cleaners.",
        "Get a quote", "See what's included", "photo-1581578731548-c64695cc6952", G1, _vid("professional home cleaning"),
        ("Cleaning plans", "The same team, on the same day, every time.", [
            ("Recurring cleans", "Weekly or biweekly with a fixed checklist and the same two cleaners each visit.", "Repeat"),
            ("Deep cleans", "Baseboards, inside appliances, grout and vents — the once-a-year reset.", "Sparkles"),
            ("Move in / move out", "Empty-property clean to a landlord-grade checklist, photographed on completion.", "Truck")]),
        [("Same", "Team every visit"), ("Eco", "Certified products only"), ("$2M", "Insured and bonded"), ("97%", "Client retention")],
        [("Four years, never once had to ask them to come back for something.", "Elaine Foster", "Client"),
         ("Move-out clean got our full deposit back. The photos did the arguing for us.", "Kojo Mensah", "Client")],
        [("Do I need to be home?", "No — most clients give us a code or key, held under a signed key agreement."),
         ("What products do you use?", "Eco-certified and fragrance-free by default; we'll use yours on request."),
         ("Can I skip a week?", "Yes, with 48 hours notice and no penalty.")],
        ("Salaried cleaners, not a gig roster.", "Clearview pays hourly staff rather than piece rates, which is why you get the same faces each visit and why the checklist is actually finished. Everyone is bonded, insured and trained in house."),
        [("Nadine Sowah", "Founder"), ("Marta Kalinowska", "Operations manager"), ("Ella Byrne", "Team lead"), ("Rafael Duarte", "Quality lead")],
        "quotes@clearviewcleaning.com", "(416) 555-0157", "45 Commerce Court, Unit 12")),
    ("music_school", _mk("Northline Music Academy", "Music Education", "RCM aligned · Ages 5 to adult",
        "Lessons kids ask to go to.",
        "One-to-one and group instruction in piano, guitar, strings and voice, with two recitals a year.",
        "Book a trial lesson", "Meet the teachers", "photo-1514320291840-2e0a9bf2a9ae", G3, _vid("music school lessons"),
        ("Programs", "Structured enough to progress, loose enough to enjoy.", [
            ("Private lessons", "Weekly 30, 45 or 60 minute lessons with a teacher matched to age and goals.", "Music"),
            ("Group & ensemble", "Bands, choirs and chamber groups where students learn to play with other people.", "Users"),
            ("Exam preparation", "RCM and conservatory prep including theory, ear training and mock exams.", "GraduationCap")]),
        [("2", "Recitals every year"), ("96%", "Exam pass rate"), ("640", "Students enrolled"), ("18", "Instruments taught")],
        [("She practises without being asked now. I still can't quite believe it.", "Rachel Adeyemi", "Parent"),
         ("Started guitar at 54. Playing in the adult ensemble within a year.", "Peter Lindgren", "Adult student")],
        [("Do you rent instruments?", "Yes, rent-to-own on strings, brass and woodwind, and we'll help you choose."),
         ("What if we miss a lesson?", "One make-up per term with 24 hours notice."),
         ("Do you teach adults?", "About a third of our students are adults, including complete beginners.")],
        ("A school built by working musicians.", "Northline's teachers all perform as well as teach, which changes how they explain things. We pair every student with a teacher by temperament as much as by instrument, and we put everyone on a stage twice a year."),
        [("Elena Vasquez", "Director, piano"), ("Marcus Bell", "Guitar & bass"), ("Sofia Ilic", "Strings"), ("Daniel Osei", "Voice & choir")],
        "enrol@northlinemusic.com", "(416) 555-0163", "212 Bloor Street West, Studio 5")),
    ("nonprofit", _mk("Riverbend Community Trust", "Nonprofit", "Registered charity · 91¢ to programs",
        "Small charity. Stubbornly local.",
        "Food security, youth mentoring and newcomer support delivered in this neighbourhood, funded by the people who live in it.",
        "Join us", "See our impact report", "photo-1559027615-cd4628902d4a", G3, _vid("community charity volunteers"),
        ("Programs", "Three programs, done properly.", [
            ("Food security", "A dignified market-model pantry serving 400 households a week, no referral needed.", "ShoppingBasket"),
            ("Youth mentoring", "Two-year mentor matches for students aged 12 to 18, with 84% staying in school.", "Users"),
            ("Newcomer support", "Language circles, credential help and housing navigation for new arrivals.", "Globe")]),
        [("91¢", "Of every dollar to programs"), ("400", "Households served weekly"), ("84%", "Youth staying in school"), ("2,100", "Volunteer hours a year")],
        [("The pantry felt like shopping, not like charity. That difference matters more than people think.", "Program participant", "Riverbend"),
         ("My mentor is the reason I applied to college at all.", "Youth alum", "Class of 2024")],
        [("How is my donation used?", "91 cents of every dollar goes directly to programs; our audited statements are published each spring."),
         ("Can I volunteer?", "Yes — pantry shifts, mentoring and board committees, with training provided."),
         ("Are donations tax deductible?", "Yes, receipts are issued for anything over $20.")],
        ("Founded at a kitchen table in 2013.", "Riverbend started when eleven neighbours pooled grocery money during a plant closure. We've stayed deliberately small and local: no national campaigns, no telemarketing, and a board that lives inside the catchment we serve."),
        [("Grace Ampofo", "Executive director"), ("Hannah Weiss", "Programs manager"), ("Omar Haddad", "Volunteer coordinator"), ("Tessa Moreau", "Board chair")],
        "hello@riverbendtrust.org", "(416) 555-0111", "8 Riverbend Road")),
    ("architecture", _mk("Vellum Architecture", "Architecture", "OAA registered · Residential & civic",
        "Buildings that know where they are.",
        "Residential, civic and adaptive-reuse architecture from concept through construction administration.",
        "Request a consultation", "View selected works", "photo-1487958449943-2429e8be8625", G3, _vid("architecture studio design process"),
        ("Practice", "Drawn, permitted and seen through to site.", [
            ("Residential", "New builds and deep renovations designed around light, storage and how you actually live.", "Home"),
            ("Civic & institutional", "Libraries, community centres and schools delivered through public procurement.", "Landmark"),
            ("Adaptive reuse", "Heritage-sensitive conversions that keep the structure and change the purpose.", "Recycle")]),
        [("34", "Projects on site or permitted"), ("2", "OAA design awards"), ("100%", "Projects with site supervision"), ("2011", "Studio founded")],
        [("They fought for the clerestory when the budget got tight. It's the best thing about the house.", "Ingrid & Paul Reyes", "Private clients"),
         ("On budget, permitted first submission, and the community actually likes it.", "Township of Ridgeway", "Civic client")],
        [("What are your fees?", "Percentage of construction cost for full service, or fixed fee for defined scopes."),
         ("Do you handle permits?", "Yes — zoning review, committee of adjustment and building permit are all in scope."),
         ("Can you work with our builder?", "Gladly, and we stay on through construction administration.")],
        ("A studio of nine, on purpose.", "Vellum stays small so a principal is on every project from sketch to site. We model in daylight and in section first, and we don't hand a set to a contractor we haven't stood on site with."),
        [("Aya Tanaka", "Principal, OAA"), ("Julian Ferreira", "Associate, OAA"), ("Nora Blackwood", "Project architect"), ("Emeka Obi", "Designer")],
        "studio@vellumarchitecture.com", "(416) 555-0125", "3rd Floor, 210 Spadina Avenue")),
]

# Studio-2026 design tokens, one identity per new template.
_LOOKS2 = {
    "veterinary": ("light", "#0E9F6E", "#F6C177", "#FFFFFF", "#F5F7F5", "#E3EBE5", "#111111", "#555555", "Fraunces", "DM Sans", 18, "clinical", "split"),
    "dental": ("light", "#2563EB", "#22D3EE", "#FFFFFF", "#F4F7FF", "#DEE7FB", "#111111", "#555555", "Plus Jakarta Sans", "Inter", 16, "campus", "split"),
    "accounting": ("light", "#1E3A5F", "#B08D57", "#FFFFFF", "#F5F5F0", "#E4E2D8", "#111111", "#555555", "Lora", "Inter", 6, "ledger", "split"),
    "landscaping": ("dark", "#4D7C0F", "#FACC15", "#12150F", "#1A1F16", "#2B3324", "#F4F7EE", "#A8B39C", "Archivo", "Inter", 4, "industrial", "cover"),
    "photography": ("dark", "#E2E8F0", "#F43F5E", "#08080A", "#111114", "#26262C", "#FFFFFF", "#A1A1AA", "Syne", "Inter", 0, "noir", "cover"),
    "automotive": ("dark", "#EF4444", "#94A3B8", "#111214", "#1A1C20", "#2E323A", "#F8FAFC", "#9CA3AF", "Oswald", "Inter", 2, "concrete", "cover"),
    "beauty": ("light", "#B48A78", "#2F4F4A", "#FFFFFF", "#FAF5F1", "#EFE3DA", "#111111", "#555555", "Cormorant Garamond", "DM Sans", 14, "editoriallux", "split"),
    "insurance": ("dark", "#0EA5E9", "#C6A15B", "#0B1220", "#141C2B", "#243248", "#F1F5F9", "#94A3B8", "Playfair Display", "Inter", 6, "harbour", "split"),
    "pet_grooming": ("light", "#F97316", "#0E9F6E", "#FFFFFF", "#FFF7ED", "#F5E2CE", "#111111", "#555555", "Nunito", "Nunito", 20, "campus", "split"),
    "hvac_plumbing": ("dark", "#0284C7", "#F59E0B", "#101418", "#181D23", "#2A333D", "#F1F5F9", "#94A3B8", "Barlow Condensed", "Inter", 2, "freight", "cover"),
    "coworking": ("light", "#4F46E5", "#F59E0B", "#FFFFFF", "#F5F5F0", "#E4E4E7", "#111111", "#555555", "Space Grotesk", "Inter", 14, "saas", "split"),
    "wellness": ("light", "#0F766E", "#94A3B8", "#FFFFFF", "#F2F7F6", "#DCE8E6", "#111111", "#555555", "Fraunces", "DM Sans", 18, "clinical", "split"),
    "cleaning": ("light", "#0891B2", "#84CC16", "#FFFFFF", "#F5F5F0", "#E2E8F0", "#111111", "#555555", "Plus Jakarta Sans", "Inter", 12, "realty", "split"),
    "music_school": ("dark", "#A855F7", "#FACC15", "#0B0A10", "#15121C", "#272033", "#FAFAFA", "#A1A1AA", "Syne", "Inter", 8, "cinematic", "cover"),
    "nonprofit": ("light", "#15803D", "#F97316", "#FFFFFF", "#F5F5F0", "#E1E7DE", "#111111", "#555555", "Nunito", "Inter", 16, "campus", "split"),
    "architecture": ("dark", "#D4D4D8", "#4F46E5", "#0A0A0B", "#141416", "#26262A", "#FFFFFF", "#A1A1AA", "Archivo", "Inter", 0, "noir", "split"),
}

STUDIO_KEYS = tuple(k for k, _ in _T)


def install():
    """Register the Studio pack into the shared NICHES / LOOKS tables (idempotent)."""
    from site_content import LOOK_V
    for key, niche in _T:
        NICHES.setdefault(key, niche)
        if key in LOOKS:
            continue
        mode, p, s, bg, sf, bd, fg, mut, fh, fb, r, preset, hero = _LOOKS2[key]
        NICHES[key]["primary"], NICHES[key]["secondary"] = p, s
        LOOKS[key] = dict(mode=mode, primary=p, secondary=s, bg=bg, surface=sf, border=bd, fg=fg,
                          muted=mut, font_heading=fh, font_body=fb, radius=r, preset=preset,
                          hero=hero, glass=mode == "dark", grain=mode == "dark", studio=True,
                          look_v=LOOK_V)
    return len(_T)
