"""Supabase / Postgres export for a single client.

Two ways out of this platform, same generated SQL:
  - GET  /api/apps/{app_id}/supabase/sql   → download schema + seed + RLS as one .sql file
  - POST /api/apps/{app_id}/supabase/push  → run it against the client's own Supabase Postgres
"""
import asyncio
import json
import logging
from datetime import datetime, timezone
from typing import Optional

from fastapi import Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

logger = logging.getLogger("agency.supabase_export")

# Mongo collection → Postgres table + its scalar columns (everything else lands in `data jsonb`).
TABLES = {
    "pages": ("pages", {"page_id": "text", "name": "text", "slug": "text", "order": "integer"}),
    "cms_collections": ("cms_collections", {"collection_id": "text", "name": "text", "slug": "text"}),
    "cms_items": ("cms_items", {"item_id": "text", "collection_id": "text", "title": "text", "slug": "text"}),
    "messages": ("leads", {"message_id": "text", "from_name": "text", "from_email": "text", "status": "text",
                           "score": "integer", "hot": "boolean", "form_label": "text", "created_at": "timestamptz"}),
    "submissions": ("submissions", {"submission_id": "text", "kind": "text", "created_at": "timestamptz"}),
    "bookings": ("bookings", {"booking_id": "text", "name": "text", "email": "text", "date": "text",
                              "status": "text", "created_at": "timestamptz"}),
    "cta_forms": ("forms", {"form_id": "text", "title": "text", "key": "text"}),
    "site_users": ("site_members", {"user_id": "text", "email": "text", "name": "text", "created_at": "timestamptz"}),
    "files": ("files", {"file_id": "text", "original_filename": "text", "content_type": "text",
                        "size": "bigint", "storage_path": "text", "created_at": "timestamptz"}),
    "workflows": ("workflows", {"workflow_id": "text", "name": "text", "trigger": "text", "enabled": "boolean"}),
    "activity_logs": ("activity_logs", {"action": "text", "detail": "text", "created_at": "timestamptz"}),
}
MAX_ROWS = 5000


def _lit(value) -> str:
    """Postgres literal for any Mongo value."""
    if value is None or value == "":
        return "NULL" if value is None else "''"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (dict, list)):
        value = json.dumps(value, default=str)
    return "'" + str(value).replace("'", "''") + "'"


def _ident(name: str) -> str:
    return '"' + name.replace('"', "") + '"'


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _ddl(prefix: str) -> str:
    out = [
        "-- Generated by LucioDigital. Safe to re-run: every statement is idempotent.",
        "create extension if not exists pgcrypto;",
        "",
        f"create table if not exists {_ident(prefix + 'clients')} (",
        "  tenant_id text primary key,",
        "  name text,",
        "  industry text,",
        "  description text,",
        "  data jsonb not null default '{}'::jsonb,",
        "  exported_at timestamptz not null default now()",
        ");",
        "",
    ]
    for _coll, (table, cols) in TABLES.items():
        lines = [f"create table if not exists {_ident(prefix + table)} (",
                 "  id uuid primary key default gen_random_uuid(),",
                 f"  tenant_id text not null references {_ident(prefix + 'tenants')}(tenant_id) on delete cascade,"]
        for col, typ in cols.items():
            lines.append(f"  {_ident(col)} {typ},")
        lines.append("  data jsonb not null default '{}'::jsonb")
        lines.append(");")
        lines.append(f"create index if not exists {_ident(prefix + table + '_tenant_idx')} "
                     f"on {_ident(prefix + table)} (tenant_id);")
        out.append("\n".join(lines))
        out.append("")
    return "\n".join(out)


def _rls(prefix: str) -> str:
    """Service role writes; signed-in users read only their own client rows."""
    out = ["-- Row Level Security: service_role bypasses RLS, authenticated users get read-only access",
           "-- scoped to the client ids listed in their JWT claim `tenant_ids` (a text array).", ""]
    for table in [prefix + "tenants"] + [prefix + t for t, _c in TABLES.values()]:
        col = "tenant_id"
        out += [
            f"alter table {_ident(table)} enable row level security;",
            f'drop policy if exists "read_own_tenant" on {_ident(table)};',
            f'create policy "read_own_tenant" on {_ident(table)} for select to authenticated',
            f"  using ({_ident(col)} = any (coalesce(string_to_array(nullif(current_setting('request.jwt.claims', true)::json #>> '{{tenant_ids}}', ''), ','), array[]::text[])));",
            "",
        ]
    return "\n".join(out)


async def build_sql(db, app_doc: dict, prefix: str = "lt_") -> tuple[str, dict]:
    """Full schema + seed + RLS script for one client. Returns (sql, row counts)."""
    app_id = app_doc["app_id"]
    counts: dict = {}
    parts = [f"-- {app_doc.get('name')} — Supabase export", f"-- Generated {_now()}", "",
             "begin;", "", _ddl(prefix)]

    tenant_data = {k: v for k, v in app_doc.items() if k not in ("_id", "owner_id", "preview_token", "github")}
    parts.append(
        f"insert into {_ident(prefix + 'tenants')} (tenant_id, name, industry, description, data) values "
        f"({_lit(app_id)}, {_lit(app_doc.get('name'))}, {_lit(app_doc.get('industry'))}, "
        f"{_lit(app_doc.get('description'))}, {_lit(tenant_data)}::jsonb)\n"
        "on conflict (tenant_id) do update set name = excluded.name, industry = excluded.industry, "
        "description = excluded.description, data = excluded.data, exported_at = now();\n")

    for coll, (table, cols) in TABLES.items():
        rows = await db[coll].find({"app_id": app_id}, {"_id": 0}).to_list(MAX_ROWS)
        counts[table] = len(rows)
        if not rows:
            continue
        parts.append(f"delete from {_ident(prefix + table)} where tenant_id = {_lit(app_id)};")
        col_names = ["tenant_id"] + list(cols.keys()) + ["data"]
        values = []
        for row in rows:
            vals = [_lit(app_id)] + [_lit(row.get(c)) for c in cols] + [f"{_lit(row)}::jsonb"]
            values.append("  (" + ", ".join(vals) + ")")
        parts.append(f"insert into {_ident(prefix + table)} "
                     f"({', '.join(_ident(c) for c in col_names)}) values\n" + ",\n".join(values) + ";\n")

    parts += [_rls(prefix), "commit;", ""]
    return "\n".join(parts), counts


def register(api, db, get_current_user, get_user_app, log_activity):
    from data_destinations import _decrypt

    class PushIn(BaseModel):
        connection_uri: Optional[str] = None
        table_prefix: str = "lt_"

    async def _saved_uri(app_id: str) -> Optional[str]:
        doc = await db.data_destinations.find_one({"app_id": app_id}, {"_id": 0})
        if not doc or doc.get("provider") not in ("supabase", "postgres"):
            return None
        return _decrypt(doc.get("secrets_encrypted", "")).get("connection_uri")

    def _prefix(raw: str) -> str:
        clean = "".join(c for c in (raw or "lt_") if c.isalnum() or c == "_")[:24]
        return clean or "lt_"

    @api.get("/apps/{app_id}/supabase/status")
    async def supabase_status(app_id: str, user: dict = Depends(get_current_user)):
        app_doc = await get_user_app(app_id, user)
        doc = await db.data_destinations.find_one({"app_id": app_id}, {"_id": 0}) or {}
        return {"has_saved_connection": bool(await _saved_uri(app_id)),
                "provider": doc.get("provider", "platform"),
                "tables": [t for t, _c in TABLES.values()],
                "last_push": app_doc.get("supabase_push")}

    @api.get("/apps/{app_id}/supabase/sql")
    async def supabase_sql(app_id: str, table_prefix: str = "lt_", user: dict = Depends(get_current_user)):
        app_doc = await get_user_app(app_id, user)
        sql, counts = await build_sql(db, app_doc, _prefix(table_prefix))
        name = (app_doc.get("name") or "tenant").lower().replace(" ", "-")
        await log_activity(app_id, user["user_id"], "supabase.sql",
                           f"Downloaded Supabase migration ({sum(counts.values())} rows)")
        return StreamingResponse(iter([sql.encode()]), media_type="application/sql",
                                 headers={"Content-Disposition": f"attachment; filename={name}-supabase.sql"})

    @api.post("/apps/{app_id}/supabase/push")
    async def supabase_push(app_id: str, body: PushIn, user: dict = Depends(get_current_user)):
        app_doc = await get_user_app(app_id, user)
        uri = (body.connection_uri or "").strip() or await _saved_uri(app_id)
        if not uri:
            raise HTTPException(400, "Add your Supabase connection URI, or save it under Data & Storage first.")
        if not uri.startswith(("postgres://", "postgresql://")):
            raise HTTPException(400, "Use a postgresql:// connection URI from Supabase → Project Settings → Database.")
        sql, counts = await build_sql(db, app_doc, _prefix(body.table_prefix))

        def _run():
            import psycopg2
            with psycopg2.connect(uri, connect_timeout=10) as conn:
                with conn.cursor() as cur:
                    cur.execute(sql)

        try:
            await asyncio.to_thread(_run)
        except Exception as exc:
            logger.info("supabase push failed for %s: %s", app_id, exc)
            raise HTTPException(502, f"Supabase rejected the push: {str(exc)[:180]}")

        result = {"pushed_at": _now(), "rows": counts, "total_rows": sum(counts.values()),
                  "tables": len(counts) + 1, "prefix": _prefix(body.table_prefix)}
        await db.apps.update_one({"app_id": app_id}, {"$set": {"supabase_push": result}})
        await log_activity(app_id, user["user_id"], "supabase.push",
                           f"Pushed {result['total_rows']} row(s) into the client's Supabase project")
        return {"ok": True, **result}
