from datetime import datetime, timezone
from fastapi import HTTPException, Depends

# Prebuilt industry templates → applied as App Mode blueprints (screens/components/models) + light theme with industry palette.
P = {"amber": ("#F59E0B", "#0F172A"), "orange": ("#F97316", "#1E293B"), "teal": ("#0D9488", "#0F766E"), "navy": ("#1E3A8A", "#10B981"), "violet": ("#7C3AED", "#EC4899"),
     "terracotta": ("#C2410C", "#F59E0B"), "red": ("#B45309", "#F97316"), "blue": ("#475569", "#0EA5E9"), "indigo": ("#4F46E5", "#22D3EE"), "emerald": ("#166534", "#0EA5E9"),
     "rose": ("#E11D48", "#F59E0B"), "slate": ("#7F1D1D", "#B45309"), "green": ("#16A34A", "#F59E0B"), "cyan": ("#4338CA", "#F59E0B"), "purple": ("#9333EA", "#F472B6"), "sky": ("#0284C7", "#F97316"), "lime": ("#65A30D", "#0D9488"), "brown": ("#92400E", "#D97706")}

# key: (name, industry, palette, [ (screen, route, [ (comp_type, label, model, [fields]) ]) ], [ (model, [field:type*]) ])
T = {
 "health_safety": ("Health & Safety Management", "Health & Safety", "amber",
  [("Dashboard", "/", [("stats", "Safety KPIs", "", ["Total Incidents", "Open Risk Items", "Compliance Rate", "Overdue Actions"]), ("chart", "Incident trend", "incidents", []), ("table", "Recent incidents", "incidents", ["Date", "Location", "Type", "Severity", "Status"])]),
   ("Report Incident", "/incidents/new", [("form", "Incident report", "incidents", ["Date", "Location", "Type", "Severity", "Description"])]),
   ("Incident Log", "/incidents", [("kanban", "Status workflow", "incidents", ["Open", "Under Review", "Resolved"]), ("table", "All incidents", "incidents", ["Date", "Type", "Severity", "Assigned To", "Status"])]),
   ("Risk Assessments", "/risks", [("table", "Likelihood × impact matrix", "risks", ["Hazard", "Likelihood", "Impact", "Rating", "Owner"]), ("form", "New assessment", "risks", ["Hazard", "Likelihood", "Impact", "Controls"])]),
   ("Compliance", "/compliance", [("list", "Checklist", "checklist_items", ["Requirement", "Due", "Status"])]),
   ("Safety Records", "/employees", [("table", "Employee records", "employees", ["Name", "Role", "Training", "Cert Expiry"])])],
  [("incidents", ["date:date*", "location:string*", "type:enum*", "severity:enum*", "description:text", "status:enum", "assigned_to:string"]), ("risks", ["hazard:string*", "likelihood:number*", "impact:number*", "controls:text", "owner:string"]), ("checklist_items", ["requirement:string*", "due:date", "status:enum"]), ("employees", ["name:string*", "role:string", "training:text", "cert_expiry:date"])]),
 "construction": ("Construction", "Construction", "orange",
  [("Dashboard", "/", [("stats", "Project status", "", ["Active Sites", "Milestones Due", "Budget Burn %", "Open Incidents"]), ("chart", "Budget burn", "projects", []), ("table", "Sites", "projects", ["Project", "Site", "Milestone", "Budget", "Status"])]),
   ("Subcontractors", "/subs", [("table", "Directory", "subcontractors", ["Company", "Trade", "Contact", "Insurance Exp"])]), ("Site Logs", "/logs", [("form", "Daily log", "site_logs", ["Date", "Site", "Weather", "Crew", "Notes"]), ("list", "Entries", "site_logs", ["Date", "Site", "Notes"])]),
   ("Deliveries", "/deliveries", [("table", "Material deliveries", "deliveries", ["Material", "Supplier", "ETA", "Status"])]), ("Permits", "/permits", [("list", "Permit checklist", "permits", ["Permit", "Authority", "Status"])]), ("Safety", "/safety", [("form", "Log incident", "incidents", ["Date", "Site", "Severity", "Description"])])],
  [("projects", ["name:string*", "site:string", "milestone:string", "budget:number", "spent:number", "status:enum"]), ("subcontractors", ["company:string*", "trade:string", "contact:email", "insurance_exp:date"]), ("site_logs", ["date:date*", "site:string", "weather:string", "crew:number", "notes:text"]), ("deliveries", ["material:string*", "supplier:string", "eta:date", "status:enum"]), ("permits", ["permit:string*", "authority:string", "status:enum"]), ("incidents", ["date:date*", "site:string", "severity:enum", "description:text"])]),
 "hvac": ("HVAC", "HVAC", "sky", [("Dashboard", "/", [("stats", "Today", "", ["Jobs Today", "Techs Active", "Contracts Due", "Low-stock Parts"]), ("calendar", "Job schedule", "jobs", [])]), ("Dispatch", "/dispatch", [("kanban", "Technician board", "jobs", ["Unassigned", "En route", "On site", "Done"])]), ("Equipment", "/equipment", [("table", "Service history", "equipment", ["Unit", "Customer", "Last Service", "Next Due"])]), ("Contracts", "/contracts", [("table", "Maintenance contracts", "contracts", ["Customer", "Plan", "Renewal", "Status"])]), ("Parts", "/parts", [("table", "Inventory", "parts", ["Part", "Qty", "Min", "Supplier"])])],
  [("jobs", ["customer:string*", "date:date*", "technician:string", "status:enum", "notes:text"]), ("equipment", ["unit:string*", "customer:string", "last_service:date", "next_due:date"]), ("contracts", ["customer:string*", "plan:string", "renewal:date", "status:enum"]), ("parts", ["part:string*", "qty:number*", "min_qty:number", "supplier:string"])]),
 "plumbing": ("Plumbing", "Plumbing", "blue", [("Dashboard", "/", [("stats", "Service", "", ["Scheduled", "In Progress", "Completed", "Emergencies"]), ("kanban", "Job tracker", "jobs", ["Scheduled", "In Progress", "Completed"])]), ("Customers", "/customers", [("table", "CRM", "customers", ["Name", "Phone", "Address", "Last Job"])]), ("Emergency Calls", "/emergency", [("form", "Log call", "emergency_calls", ["Caller", "Phone", "Issue", "Priority"])]), ("Inventory", "/parts", [("table", "Parts & materials", "parts", ["Item", "Qty", "Cost"])]), ("Quotes & Invoices", "/billing", [("form", "Quote generator", "invoices", ["Customer", "Labor Hours", "Parts", "Total"]), ("table", "Invoices", "invoices", ["Customer", "Total", "Status"])]), ("Job Photos", "/photos", [("cards", "Site documentation", "photos", ["Job", "Caption"])])],
  [("jobs", ["customer:string*", "date:date", "status:enum", "notes:text"]), ("customers", ["name:string*", "phone:string", "address:string", "email:email"]), ("emergency_calls", ["caller:string*", "phone:string", "issue:text", "priority:enum"]), ("parts", ["item:string*", "qty:number", "cost:number"]), ("invoices", ["customer:string*", "labor_hours:number", "parts_total:number", "total:number", "status:enum"]), ("photos", ["job:string*", "url:string", "caption:string"])]),
 "carpentry": ("Carpentry", "Carpentry", "brown", [("Dashboard", "/", [("stats", "Studio", "", ["Active Projects", "Quotes Pending", "Approvals", "Deliveries"]), ("cards", "Portfolio", "projects", ["Project", "Client"])]), ("Quote Builder", "/quotes", [("form", "Custom quote", "quotes", ["Client", "Materials Cost", "Labor Hours", "Rate", "Total"])]), ("Approvals", "/approvals", [("kanban", "Client approval", "quotes", ["Sent", "Viewed", "Approved", "Declined"])]), ("Timeline", "/timeline", [("calendar", "Project timeline", "projects", [])]), ("Suppliers", "/suppliers", [("table", "Supplier contacts", "suppliers", ["Supplier", "Material", "Contact"])]), ("Gallery", "/gallery", [("cards", "Before / After", "photos", ["Project", "Stage"])])],
  [("projects", ["name:string*", "client:string", "start:date", "end:date", "status:enum"]), ("quotes", ["client:string*", "materials_cost:number", "labor_hours:number", "rate:number", "total:number", "status:enum"]), ("suppliers", ["supplier:string*", "material:string", "contact:email"]), ("photos", ["project:string*", "stage:enum", "url:string"])]),
 "electrical": ("Electrical", "Electrical", "lime", [("Dashboard", "/", [("stats", "Overview", "", ["Open Job Cards", "Inspections Due", "Certs Expiring", "Unpaid Invoices"]), ("table", "Job cards", "job_cards", ["Job", "Customer", "Status", "Due"])]), ("Inspections", "/inspections", [("list", "Compliance checklist", "inspections", ["Item", "Result", "Date"])]), ("Documents", "/vault", [("cards", "Contractor vault", "documents", ["Document", "Expires"])]), ("Load Calcs", "/loads", [("form", "Circuit & load", "load_calcs", ["Circuit", "Voltage", "Amps", "Load kW"]), ("table", "Log", "load_calcs", ["Circuit", "Load kW", "Date"])]), ("Billing", "/billing", [("table", "Customer billing", "invoices", ["Customer", "Amount", "Status", "Date"])]), ("Certifications", "/certs", [("table", "Safety certs", "certifications", ["Name", "Cert", "Expires"])])],
  [("job_cards", ["job:string*", "customer:string", "status:enum", "due:date"]), ("inspections", ["item:string*", "result:enum", "date:date"]), ("documents", ["name:string*", "url:string", "expires:date"]), ("load_calcs", ["circuit:string*", "voltage:number", "amps:number", "load_kw:number", "date:date"]), ("invoices", ["customer:string*", "amount:number", "status:enum", "date:date"]), ("certifications", ["name:string*", "cert:string", "expires:date"])]),
 "retail": ("Retail", "E-commerce", "violet", [("Dashboard", "/", [("stats", "Sales", "", ["Today Sales", "Orders", "Low Stock", "Loyalty Members"]), ("chart", "Daily sales", "sales", [])]), ("Catalog", "/products", [("table", "Products & inventory", "products", ["SKU", "Name", "Stock", "Price"])]), ("POS", "/pos", [("form", "New sale", "sales", ["Customer", "Items", "Total", "Payment"])]), ("Suppliers", "/suppliers", [("table", "Suppliers", "suppliers", ["Supplier", "Category", "Lead Time"])]), ("Loyalty", "/loyalty", [("table", "Customer tiers", "customers", ["Customer", "Tier", "Points"])]), ("Promotions", "/promos", [("table", "Promotions", "promotions", ["Promo", "Discount", "Ends"])])],
  [("products", ["sku:string*", "name:string*", "stock:number", "min_stock:number", "price:number"]), ("sales", ["date:date*", "customer:string", "total:number", "payment:enum"]), ("suppliers", ["supplier:string*", "category:string", "lead_time:number"]), ("customers", ["name:string*", "email:email", "tier:enum", "points:number"]), ("promotions", ["promo:string*", "discount:number", "ends:date"])]),
 "hospitality": ("Hospitality", "Hospitality", "terracotta", [("Dashboard", "/", [("stats", "Front desk", "", ["Occupancy", "Arrivals", "Departures", "Revenue"]), ("calendar", "Reservations", "reservations", [])]), ("Floor Plan", "/floor", [("cards", "Rooms & tables", "rooms", ["Room", "Status"])]), ("Guests", "/guests", [("table", "Guest profiles", "guests", ["Guest", "Stays", "Preferences"])]), ("Housekeeping", "/housekeeping", [("kanban", "Task board", "tasks", ["To clean", "In progress", "Inspected"])]), ("Check-in", "/checkin", [("table", "Arrivals & departures", "reservations", ["Guest", "Room", "Check-in", "Check-out", "Status"])]), ("Reviews", "/reviews", [("list", "Feedback", "reviews", ["Guest", "Rating", "Comment"])])],
  [("reservations", ["guest:string*", "room:string", "check_in:date*", "check_out:date*", "status:enum"]), ("rooms", ["room:string*", "type:string", "status:enum"]), ("guests", ["name:string*", "email:email", "preferences:text"]), ("tasks", ["room:string*", "status:enum", "assignee:string"]), ("reviews", ["guest:string", "rating:number", "comment:text"])]),
 "fitness": ("Fitness", "Fitness", "green", [("Dashboard", "/", [("stats", "Gym", "", ["Active Members", "Classes Today", "Renewals Due", "Attendance"]), ("chart", "Attendance", "attendance", [])]), ("Members", "/members", [("table", "Member CRM", "members", ["Member", "Plan", "Status", "Renewal"])]), ("Classes", "/classes", [("calendar", "Schedule & booking", "classes", [])]), ("Trainers", "/trainers", [("table", "Assignments", "trainers", ["Trainer", "Specialty", "Classes"])]), ("Workout Plans", "/plans", [("form", "Plan builder", "workout_plans", ["Member", "Goal", "Exercises", "Weeks"])]), ("Progress", "/progress", [("chart", "Member metrics", "progress", [])])],
  [("members", ["name:string*", "email:email", "plan:string", "status:enum", "renewal:date"]), ("classes", ["name:string*", "date:date*", "trainer:string", "capacity:number"]), ("trainers", ["name:string*", "specialty:string"]), ("workout_plans", ["member:string*", "goal:string", "exercises:text", "weeks:number"]), ("attendance", ["member:string*", "date:date*"]), ("progress", ["member:string*", "date:date", "weight:number", "notes:text"])]),
 "finance": ("Finance", "Finance", "navy", [("Dashboard", "/", [("stats", "Portfolio", "", ["AUM", "YTD Return", "Open Invoices", "Compliance Items"]), ("chart", "Performance", "portfolios", [])]), ("Transactions", "/transactions", [("table", "Ledger", "transactions", ["Date", "Client", "Type", "Amount"])]), ("Budgets", "/budgets", [("table", "Budget vs actuals", "budgets", ["Category", "Budget", "Actual", "Variance"])]), ("Invoices", "/invoices", [("table", "Invoices & payments", "invoices", ["Client", "Amount", "Due", "Status"])]), ("Reports", "/reports", [("form", "Report generator", "reports", ["Client", "Period", "Type"])]), ("Vault", "/vault", [("cards", "Documents", "documents", ["Document", "Client"])]), ("Compliance", "/compliance", [("list", "Checklist", "compliance_items", ["Item", "Status"])])],
  [("portfolios", ["client:string*", "value:number", "ytd_return:number"]), ("transactions", ["date:date*", "client:string", "type:enum", "amount:number*"]), ("budgets", ["category:string*", "budget:number", "actual:number"]), ("invoices", ["client:string*", "amount:number", "due:date", "status:enum"]), ("reports", ["client:string", "period:string", "type:string"]), ("documents", ["name:string*", "client:string", "url:string"]), ("compliance_items", ["item:string*", "status:enum"])]),
 "it_services": ("IT Services", "IT Services", "indigo", [("Dashboard", "/", [("stats", "Helpdesk", "", ["Open Tickets", "Urgent", "SLA Breaches", "Assets"]), ("kanban", "Tickets by priority", "tickets", ["Low", "Medium", "High", "Urgent"])]), ("Assets", "/assets", [("table", "Device inventory", "assets", ["Asset", "Owner", "Type", "Warranty"])]), ("SLA", "/sla", [("table", "SLA timers", "tickets", ["Ticket", "Priority", "Opened", "Due", "Remaining"])]), ("Onboarding", "/onboarding", [("list", "Client checklist", "onboarding_items", ["Step", "Client", "Done"])]), ("Network Log", "/network", [("list", "Maintenance log", "network_logs", ["Date", "System", "Action"])]), ("Licenses", "/licenses", [("table", "Software licenses", "licenses", ["Software", "Seats", "Renewal"])]), ("Team Tasks", "/tasks", [("kanban", "Task board", "tasks", ["Todo", "Doing", "Done"])])],
  [("tickets", ["title:string*", "client:string", "priority:enum*", "status:enum", "opened:date", "due:date"]), ("assets", ["asset:string*", "owner:string", "type:string", "warranty:date"]), ("onboarding_items", ["step:string*", "client:string", "done:boolean"]), ("network_logs", ["date:date*", "system:string", "action:text"]), ("licenses", ["software:string*", "seats:number", "renewal:date"]), ("tasks", ["title:string*", "assignee:string", "status:enum"])]),
 "real_estate": ("Real Estate", "Real Estate", "emerald", [("Dashboard", "/", [("stats", "Pipeline", "", ["Active Listings", "Leads", "Viewings", "Offers"]), ("chart", "Sales pipeline", "deals", [])]), ("Listings", "/listings", [("cards", "Properties", "properties", ["Address", "Price"])]), ("CRM", "/crm", [("kanban", "Lead pipeline", "leads", ["New", "Contacted", "Viewing", "Offer", "Closed"])]), ("Viewings", "/viewings", [("calendar", "Scheduler", "viewings", [])]), ("Offers", "/offers", [("table", "Negotiations", "deals", ["Property", "Buyer", "Offer", "Status"])]), ("Documents", "/documents", [("cards", "Per property", "documents", ["Document", "Property"])]), ("Commission", "/commission", [("form", "Calculator", "deals", ["Sale Price", "Rate %", "Split %", "Commission"])])],
  [("properties", ["address:string*", "price:number", "beds:number", "status:enum", "photos:text"]), ("leads", ["name:string*", "email:email", "stage:enum", "budget:number"]), ("viewings", ["property:string*", "lead:string", "date:date*"]), ("deals", ["property:string*", "buyer:string", "offer:number", "status:enum"]), ("documents", ["name:string*", "property:string", "url:string"])]),
 "education": ("Education", "Education", "cyan", [("Dashboard", "/", [("stats", "School", "", ["Students", "Classes Today", "Attendance %", "Fees Due"]), ("calendar", "Class schedule", "classes", [])]), ("Enrollment", "/students", [("table", "Students", "students", ["Student", "Grade", "Guardian", "Status"])]), ("Grades", "/grades", [("table", "Assignments & grades", "assignments", ["Assignment", "Course", "Due", "Grade"])]), ("Attendance", "/attendance", [("form", "Daily log", "attendance", ["Class", "Date", "Present", "Absent"])]), ("Parents", "/parents", [("chat", "Communication portal", "messages", [])]), ("Fees", "/fees", [("table", "Payment status", "fees", ["Student", "Amount", "Due", "Status"])]), ("Progress", "/progress", [("chart", "Student reports", "assignments", [])])],
  [("students", ["name:string*", "grade:string", "guardian:string", "guardian_email:email", "status:enum"]), ("classes", ["name:string*", "date:date*", "teacher:string"]), ("assignments", ["title:string*", "course:string", "due:date", "grade:number"]), ("attendance", ["class:string*", "date:date*", "present:number", "absent:number"]), ("messages", ["parent:string*", "body:text", "date:date"]), ("fees", ["student:string*", "amount:number", "due:date", "status:enum"])]),
 "healthcare": ("Healthcare", "Healthcare", "teal", [("Dashboard", "/", [("stats", "Clinic", "", ["Appointments Today", "Patients", "Pending Claims", "Follow-ups"]), ("calendar", "Appointments", "appointments", [])]), ("Records", "/records", [("table", "Medical records", "records", ["Patient", "Visit", "Diagnosis", "Provider"])]), ("Prescriptions", "/prescriptions", [("table", "Tracker", "prescriptions", ["Patient", "Medication", "Dose", "Refill"])]), ("Billing", "/billing", [("table", "Insurance claims", "claims", ["Patient", "Insurer", "Amount", "Status"])]), ("Staff", "/shifts", [("calendar", "Shift manager", "shifts", [])]), ("Compliance", "/compliance", [("cards", "Documents", "documents", ["Document", "Expires"])]), ("Follow-ups", "/followups", [("list", "Reminders", "followups", ["Patient", "Due", "Channel"])])],
  [("patients", ["name:string*", "dob:date", "email:email", "phone:string"]), ("appointments", ["patient:string*", "date:date*", "provider:string", "status:enum"]), ("records", ["patient:string*", "visit:date", "diagnosis:text", "provider:string"]), ("prescriptions", ["patient:string*", "medication:string*", "dose:string", "refill:date"]), ("claims", ["patient:string*", "insurer:string", "amount:number", "status:enum"]), ("shifts", ["staff:string*", "date:date*", "shift:enum"]), ("documents", ["name:string*", "expires:date"]), ("followups", ["patient:string*", "due:date", "channel:enum"])]),
 "legal": ("Legal", "Legal", "slate", [("Dashboard", "/", [("stats", "Practice", "", ["Open Cases", "Court Dates", "Unbilled Hours", "Deadlines"]), ("table", "Cases", "cases", ["Case", "Client", "Type", "Status"])]), ("Intake", "/intake", [("form", "Client intake", "clients", ["Name", "Email", "Matter", "Opposing Party"])]), ("Vault", "/vault", [("cards", "Secure documents", "documents", ["Document", "Case"])]), ("Time & Billing", "/billing", [("form", "Time entry (stopwatch)", "time_entries", ["Case", "Minutes", "Rate", "Description"]), ("table", "Entries", "time_entries", ["Case", "Minutes", "Amount", "Billed"])]), ("Court Calendar", "/calendar", [("calendar", "Court dates", "court_dates", [])]), ("Deadlines", "/tasks", [("kanban", "Tasks", "tasks", ["Todo", "In progress", "Done"])]), ("Conflict Check", "/conflicts", [("form", "Automated checker", "clients", ["Party Name"]), ("table", "Matches", "clients", ["Name", "Matter", "Opposing Party"])])],
  [("cases", ["title:string*", "client:string", "type:string", "status:enum"]), ("clients", ["name:string*", "email:email", "matter:string", "opposing_party:string"]), ("documents", ["name:string*", "case:string", "url:string"]), ("time_entries", ["case:string*", "minutes:number*", "rate:number", "description:text", "billed:boolean"]), ("court_dates", ["case:string*", "date:date*", "court:string"]), ("tasks", ["title:string*", "case:string", "due:date", "status:enum"])]),
 "restaurant": ("Restaurants", "Restaurants", "red", [("Dashboard", "/", [("stats", "Tonight", "", ["Reservations", "Covers", "Revenue", "Low Stock"]), ("chart", "Daily revenue", "orders", [])]), ("Reservations", "/reservations", [("calendar", "Tables", "reservations", [])]), ("Menu", "/menu", [("table", "Menu items", "menu_items", ["Item", "Category", "Price", "Available"])]), ("Kitchen", "/kitchen", [("kanban", "Order board", "orders", ["New", "Cooking", "Ready", "Served"])]), ("Staff", "/shifts", [("calendar", "Shift scheduler", "shifts", [])]), ("Inventory", "/inventory", [("table", "Inventory & suppliers", "inventory", ["Item", "Qty", "Supplier"])]), ("Feedback", "/feedback", [("list", "Customer feedback", "feedback", ["Guest", "Rating", "Comment"])])],
  [("reservations", ["guest:string*", "date:date*", "party_size:number", "table:string"]), ("menu_items", ["item:string*", "category:string", "price:number", "available:boolean"]), ("orders", ["table:string*", "items:text", "total:number", "status:enum", "date:date"]), ("shifts", ["staff:string*", "date:date*", "role:string"]), ("inventory", ["item:string*", "qty:number", "supplier:string"]), ("feedback", ["guest:string", "rating:number", "comment:text"])]),
 "events": ("Events", "Events", "purple", [("Dashboard", "/", [("stats", "Upcoming", "", ["Events", "RSVPs", "Budget Used", "Open Tasks"]), ("calendar", "Planning timeline", "events", [])]), ("Vendors", "/vendors", [("table", "Vendor database", "vendors", ["Vendor", "Service", "Contact", "Cost"])]), ("Guests", "/guests", [("table", "Guest list & RSVP", "guests", ["Guest", "Event", "RSVP", "Meal"])]), ("Budget", "/budget", [("table", "Budget planner", "budget_lines", ["Item", "Planned", "Actual"])]), ("Tasks", "/tasks", [("kanban", "Assignments", "tasks", ["Todo", "Doing", "Done"])]), ("Venue", "/venue", [("list", "Venue checklist", "checklist", ["Item", "Done"])]), ("Reports", "/reports", [("form", "Post-event report", "events", ["Event", "Attendance", "Spend", "Highlights"])])],
  [("events", ["name:string*", "date:date*", "venue:string", "budget:number"]), ("vendors", ["vendor:string*", "service:string", "contact:email", "cost:number"]), ("guests", ["name:string*", "event:string", "rsvp:enum", "meal:string"]), ("budget_lines", ["item:string*", "planned:number", "actual:number"]), ("tasks", ["title:string*", "assignee:string", "status:enum"]), ("checklist", ["item:string*", "done:boolean"])]),
 "logistics": ("Logistics", "Internal Tools", "amber", [("Dashboard", "/", [("stats", "Fleet", "", ["Vehicles Active", "Shipments", "Late Deliveries", "SLA %"]), ("kanban", "Shipment board", "shipments", ["Booked", "In transit", "Out for delivery", "Delivered"])]), ("Fleet", "/fleet", [("table", "Vehicles & drivers", "vehicles", ["Vehicle", "Driver", "Status", "Next Service"])]), ("Deliveries", "/deliveries", [("table", "Status board", "shipments", ["Shipment", "Client", "ETA", "Status"])]), ("Routes", "/routes", [("list", "Route planner notes", "routes", ["Route", "Stops", "Notes"])]), ("Fuel & Maintenance", "/maintenance", [("table", "Log", "maintenance", ["Vehicle", "Type", "Cost", "Date"])]), ("Billing", "/billing", [("form", "Client invoice", "invoices", ["Client", "Shipments", "Amount"])]), ("SLA", "/sla", [("chart", "Compliance", "shipments", [])])],
  [("vehicles", ["vehicle:string*", "driver:string", "status:enum", "next_service:date"]), ("shipments", ["ref:string*", "client:string", "eta:date", "status:enum"]), ("routes", ["route:string*", "stops:number", "notes:text"]), ("maintenance", ["vehicle:string*", "type:enum", "cost:number", "date:date"]), ("invoices", ["client:string*", "amount:number", "status:enum"])]),
}


def build_spec(key: str) -> dict:
    name, industry, pal, screens, models = T[key]
    p, s = P[pal]
    return {"name": name, "tagline": f"Prebuilt {industry} operations suite · light mode · sidebar navigation", "template": key, "palette": pal,
            "screens": [{"name": sn, "route": r, "description": f"{sn} for {name}", "nav": True, "components": [{"type": ct, "label": lb, "model": m, "fields": f} for ct, lb, m, f in comps]} for sn, r, comps in screens],
            "models": [{"name": mn, "fields": [{"name": fl.rstrip("*").split(":")[0], "type": fl.rstrip("*").split(":")[1], "required": fl.endswith("*")} for fl in fs]} for mn, fs in models],
            "api": [{"method": mth, "path": f"/api/{mn}" + ("/{id}" if mth in ("PUT", "DELETE") else ""), "description": f"{mth} {mn}"} for mn, _ in models for mth in ("GET", "POST", "PUT", "DELETE")],
            "roles": ["admin", "manager", "staff"], "integrations": ["Supabase", "Stripe", "Email"],
            "theme": {"mode": "light", "primary": p, "secondary": s, "bg": "#F8FAFC", "surface": "#FFFFFF", "fg": "#0F172A", "radius": 14, "motion": True, "cursor": True}}


def register(api, db, get_current_user, get_user_app, log_activity, install_defaults=None):
    @api.get("/templates")
    async def list_templates(user: dict = Depends(get_current_user)):
        return [{"key": k, "name": v[0], "industry": v[1], "primary": P[v[2]][0], "secondary": P[v[2]][1], "screens": len(v[3]), "models": len(v[4]),
                 "suite": "Health & Safety" if k == "health_safety" else "Contractor" if k in ("construction", "hvac", "plumbing", "carpentry", "electrical") else "Enterprise"} for k, v in T.items()]

    @api.post("/apps/{app_id}/templates/{key}/apply")
    async def apply_template(app_id: str, key: str, user: dict = Depends(get_current_user)):
        await get_user_app(app_id, user)
        if key not in T:
            raise HTTPException(404, "Project not found")
        spec = build_spec(key)
        spec["generated_at"] = datetime.now(timezone.utc).isoformat()
        theme = spec.pop("theme")
        # Each industry template carries its own unique visual identity (site_content.LOOKS).
        from site_content import LOOKS, NICHES, theme_for, INDUSTRY_MAP
        nk = key if key in LOOKS else INDUSTRY_MAP.get(T[key][1].lower().strip())
        theme = theme_for(NICHES[nk], nk) if nk in LOOKS else {**theme, "font_heading": "Plus Jakarta Sans", "font_body": "Manrope", "muted": "#64748B", "border": "#E2E8F0"}
        await db.apps.update_one({"app_id": app_id}, {"$set": {"app_spec": spec, "kind": "app", "industry": T[key][1], "site_niche": nk if nk in LOOKS else None, "theme": theme}})
        await log_activity(app_id, user["user_id"], "template.applied", f"Applied project: {spec['name']}")
        return {"spec": spec, "theme": theme}
